---
name: Exception-Class-Nested
version: 0.02
author:
  - 'Jenda Krynicky, <jenda@krynicky.cz>'
abstract: Nested declaration of Exception::Class classes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exception::Class: 1
provides:
  Exception::Class::Nested:
    file: lib/Exception/Class/Nested.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
